llm_chain:
    platform:
        openai:
            api_key: '%env(OPENAI_API_KEY)%'
    chains:
        default:
            model:
                name: 'GPT'
                version: 'gpt-4o-mini'
                options: []
